osx_image: xcode10.1
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- brew update
- brew outdated xctool || brew upgrade xctool
script:
- xcodebuild test -workspace Example/KMNavigationBar.xcworkspace -scheme KMNavigationBar-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.0' build-for-testing ONLY_ACTIVE_ARCH=NO
- xctool run-tests -workspace Example/KMNavigationBar.xcworkspace -scheme KMNavigationBar-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --allow-warnings
- pod spec lint --allow-warnings
# - pod trunk push --allow-warnings